-- Schema for the screening-llm-judge-playground evaluation warehouse.
-- Designed for the CSV columns A–M defined in src/csv_processor.py and the
-- JudgeResult shape in src/llm_judge.py. Run as a role with CREATE on the schema.
--
-- Suggested location:
--   DATABASE  = LLM_JUDGE
--   SCHEMA    = SCREENING
--   WAREHOUSE = LLM_JUDGE_WH (small is plenty for this volume)

CREATE DATABASE IF NOT EXISTS LLM_JUDGE;
CREATE SCHEMA   IF NOT EXISTS LLM_JUDGE.SCREENING;

USE SCHEMA LLM_JUDGE.SCREENING;

-- One row per CSV record (the human ground truth side of the evaluation).
-- Mirrors the columns in src/csv_processor.py (Date, Link, Candidate Name, ...).
CREATE TABLE IF NOT EXISTS CSV_HUMAN_LABELS (
    CALL_ID            STRING       NOT NULL,
    REF_NUM            STRING       NOT NULL,           -- "Tenant" column L
    ROW_NUMBER         NUMBER       NOT NULL,           -- 1-based row in source CSV
    CSV_SOURCE         STRING,                          -- file name / batch id
    LINK               STRING,
    CANDIDATE_NAME     STRING,
    COMMENTS           STRING,                          -- column D, free text
    AI_RATING          NUMBER(3,1),                     -- column E
    CANDIDATE_RATING   NUMBER(3,1),                     -- column F (human label)
    ISSUE_CATEGORIES   ARRAY,                           -- column G, parsed CSV
    ANNOTATOR_NAME     STRING,
    REVIEWED_BY        STRING,
    WEEK_NUMBER        NUMBER,
    MONTH              STRING,
    SCREENING_DATE     DATE,
    LOADED_AT          TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CSV_HUMAN_LABELS PRIMARY KEY (CALL_ID, REF_NUM)
);

-- One row per Gemini judge invocation produced by src/llm_judge.py::run_judge.
-- Captures enough metadata to compare prompts, models, and context flags over time.
CREATE TABLE IF NOT EXISTS JUDGE_RUNS (
    RUN_ID             STRING        NOT NULL,         -- uuid generated by sink
    RUN_AT             TIMESTAMP_NTZ NOT NULL,
    CALL_ID            STRING        NOT NULL,
    REF_NUM            STRING        NOT NULL,
    ROW_NUMBER         NUMBER,
    MODEL              STRING,                          -- e.g. gemini-2.5-flash
    PROMPT_VERSION     STRING,                          -- short sha of prompt text
    PROMPT_TEXT        STRING,
    INCLUDE_TRANSCRIPT BOOLEAN,
    INCLUDE_KB         BOOLEAN,
    INCLUDE_JD         BOOLEAN,
    INCLUDE_AUDIO      BOOLEAN,
    RAW_OUTPUT         STRING,
    LLM_ISSUE_CATEGORY STRING,                          -- parsed first line / label
    LLM_RATING         NUMBER(3,1),                     -- parsed if present
    LATENCY_MS         NUMBER,
    ERROR              STRING,
    CONSTRAINT PK_JUDGE_RUNS PRIMARY KEY (RUN_ID)
);

-- Convenience view: every judge run joined to the human label, with a numeric
-- rating gap and a flag for whether the LLM picked any of the human-tagged
-- issue categories. Use this as the base for evaluation dashboards.
CREATE OR REPLACE VIEW V_JUDGE_VS_HUMAN AS
SELECT
    r.RUN_ID,
    r.RUN_AT,
    r.MODEL,
    r.PROMPT_VERSION,
    r.INCLUDE_TRANSCRIPT,
    r.INCLUDE_KB,
    r.INCLUDE_JD,
    r.INCLUDE_AUDIO,
    r.CALL_ID,
    r.REF_NUM AS TENANT,
    h.CANDIDATE_NAME,
    h.CANDIDATE_RATING       AS HUMAN_RATING,
    r.LLM_RATING,
    (r.LLM_RATING - h.CANDIDATE_RATING) AS RATING_GAP,
    h.ISSUE_CATEGORIES       AS HUMAN_ISSUES,
    r.LLM_ISSUE_CATEGORY,
    CASE
        WHEN r.LLM_ISSUE_CATEGORY IS NULL THEN NULL
        WHEN ARRAY_CONTAINS(r.LLM_ISSUE_CATEGORY::variant, h.ISSUE_CATEGORIES) THEN TRUE
        ELSE FALSE
    END                       AS LLM_PICKED_HUMAN_ISSUE,
    h.COMMENTS                AS HUMAN_COMMENTS,
    r.RAW_OUTPUT              AS LLM_OUTPUT,
    r.ERROR
FROM JUDGE_RUNS r
LEFT JOIN CSV_HUMAN_LABELS h
       ON h.CALL_ID = r.CALL_ID
      AND h.REF_NUM = r.REF_NUM;
